# Generated by Django 4.2.11 on 2024-03-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Vazio', max_length=20)),
                ('desc', models.CharField(default='Sem conteúdo', max_length=100)),
                ('data_vencimento', models.DateField()),
                ('prioridade', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
